PUTBASIC "src/HOTEL1.bas","HOTEL1"
PUTBASIC "src/HOTEL2.bas","HOTEL2"
PUTBASIC "src/HOTELSP.bas","HOTELSP"
PUTFILE "src/SPDATA.bin","SPDATA",&4F00,&4F00
PUTFILE "src/HOTELSC.bin","HOTELSC",&5E40,&5E40
PUTTEXT "src/BOOT.txt", "!BOOT",&FFFF